 <!--  Quick Picks Section -->
 <ul id="quickpicks" style="padding-top:1.5em;"> 
<li style="padding-left: 2em;"><a href="https://server.iad.liveperson.net/hc/64904228/?cmd=file&file=visitorWantsToChat&site=64904228&SV!skill=Ryerson&LEAppKey=f907f2d9acd64b7f8c00b83bed3c2822&referrer=http%3A//library.ryerson.ca/info/contactus/&bId=16" data-ga-event="Homepage,QuickPick,Askus">
<img alt="Need Help? Ask Us" src="/wp-content/uploads/AskUs.png" class="alignnone wp-image-64 noborder" height="60" width="60">Live<br>Chat</a></li>
<li style="padding-left: 2em;"><a href="http://library.ryerson.ca/guides/book-an-appointment/" data-ga-event="Homepage,QuickPick,Appointment"><img src="/wp-content/uploads/BookLibrarian.png" alt="" class="alignnone size-full wp-image-10021" height="60" width="60" />Book a<br>Librarian</a></li> 
<li style="padding-left: 2em;"><a href="http://catalogue.library.ryerson.ca/patroninfo" data-ga-event="Homepage,QuickPick,Renew"><img src="/wp-content/uploads/Renew.png" alt="Library Account" title="Borrower Account - Renew, Check Fines"  class="alignnone size-full wp-image-65" height="60" width="60" />Renew</a></li> 
<li style="padding-left: 2em;"><a href="http://library.ryerson.ca/info/whats-new/workshops-and-events/" data-ga-event="Homepage,QuickPick,Workshops"><img src="/wp-content/uploads/Workshops.png" alt=""  class="alignnone size-full wp-image-72" height="60" width="60" />Workshops &amp; Events</a> </li> 
<li style="padding-left: 2em;"><a href="http://racer.scholarsportal.info/" data-ga-event="Homepage,QuickPick,RACER"><img src="/wp-content/uploads/RACER.png" alt="RACER" title="Borrow items from other libraries"  class="alignnone size-full" height="60" width="60" />InterLibrary Loan</a></li>
<li style="padding-left: 2em;"><a href="http://learn.library.ryerson.ca/citationhelp/managers" data-ga-event="Homepage,QuickPick,Refworks"><img src="/wp-content/uploads/CitationManagement.png" alt="" title="Bibliographic citation tool"  class="alignnone wp-image-64" height="72" width="72" />Citation Tools</a></li> 
<li style="padding-left: 2em;"><a href="/gmdc/" data-ga-event="Homepage,QuickPick,Geospatial" data-ga-event="Homepage,QuickPick,GMDC"><img src="/wp-content/uploads/Geospatial.png" alt=""  class="alignnone size-full wp-image-64" height="60" width="60" />Geodata Maps <br>Statistics</a></li>
<li style="padding-left: 2em;"><a href="https://cas.ryerson.ca/login?service=https%3A%2F%2Fmy.ryerson.ca%2FLogin" data-ga-event="Homepage,QuickPick,Blackboard"><img src="/wp-content/uploads/D2L.png" alt="D2L"  class="alignnone size-full wp-image-64" height="60" width="60" />my.ryerson</a></li>
<li style="padding-left: 2em;"><a href="http://library.ryerson.ca/services/faculty/" data-ga-event="Homepage,QuickPick,Faculty"><img src="/wp-content/uploads/ServicesFaculty.png" alt="" class="alignnone size-full wp-image-64" height="60" width="60" />Services for Faculty</a></li>
<li style="padding-left: 2em;"><a href="http://library.ryerson.ca/services/reserve/" data-ga-event="Homepage,QuickPick,ereserve"><img src="/wp-content/uploads/CourseReading.png" alt="e-reserve" class="alignnone size-full wp-image-64" height="60" width="60" />Course Readings</a></li> 
</ul>
 <!--  End of: QuickPicks Section -->